### ISSUE TITLE
trip reports page should use month + year format

### ISSUE THREAD

**Issue by cmosetick** [turns-all-year/tay#5]
The trip reports overview page should use the `month + year` format that the existing site uses.
e.g.

__2017 Trip reports__
* June 2017
* May 2017
* April 2017

This is critical as users need to be able to reference specific months from previous years to get ideas for outings and past conditions found in those trip reports.

What I envision is a URL & navigation structure that is simple to follow:
e.g.
`http://example.com/trip-reports/2017/06/`
should give a listing overview of all trip reports from June 2017

Where as actual trip reports themselves could live underneath the users profile:
`http://example.com/user/cmosetick/2017/05/15/mt-hood-summit-trip`

All trip reports should be put into a chronological order based on the month of the trip report. (not when it was written or posted/updated). The trip reports submission page includes a specific date field so that a user can easily specify when an outing actually occurred. The date from this field is what determines where the trip report actually lives for navigation purposes.

**Comment by cmosetick** [comment]
@bsidelinger912 This is looking really good! Is there an easy way to make previous years be auto-collapsed, so that all the months are not listed unless a user clicks/taps on the year or dropdown box?

I also realize that based on previous discussions, there will not be any previous years present immediately, if we do not import old trip reports into the new site. But this is still core functionality that I'd like to have figured out before launching.

**Comment by bsidelinger912** [comment]
Yeah, that'd be no problem at all.
