### ISSUE TITLE
issue with SASS on latest commit

### ISSUE THREAD

**Issue by cmosetick** [turns-all-year/tay#6]
Here is what I get on branch master when I run `npm run dev`

```
ERROR in ../~/css-loader?{"localIdentName":"[hash:base64]-[name]-[local]","modules":true}!../~/sass-loader/lib/loader.js!./web/pages/Trip/trip.scss
Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)
```

**Comment by bsidelinger912** [comment]
Looks like you need to run `$ npm rebuild node-sass`.  I think it's this issue: https://github.com/sass/node-sass/issues/1764

**Comment by cmosetick** [comment]
Thanks for that info. Based on that I decided to run:
`yarn install --force`
which seems to be the equivalent with yarn.

It's got me back up and running so thanks very much @bsidelinger912!
